[tox]
env_list =
    linting
    py{311,312,313,314}

[testenv]
extras = all
dependency_groups = test
commands = pytest {posargs:-n auto}


[testenv:linting]
runner = uv-venv-lock-runner
package = editable
dependency_groups = lint
commands = pre-commit run --all-files --show-diff-on-failure
