version: 1
disable_existing_loggers: false
handlers:
  console:
    class: common_libs.logging.ColoredStreamHandler
    formatter: default
    stream: ext://sys.stdout
formatters:
  default:
    class: common_libs.logging.LogFormatter
loggers:
  common_libs:
    level: INFO
    handlers:
      - console
    propagate: false
